name: Craco
on:
  push: {}

jobs:
  craco:
    uses: 'sfusurge/actions-workflows/.github/workflows/npm-publish.yml@v1'
    with:
      workflow-ref: "v1"
      package: "config/craco"
      publish-gpr: ${{ startsWith(github.ref, 'refs/tags/v') }}
      replace-version: "${{ github.ref_name }}"
