name: Eslint
on:
  push: {}

jobs:
  eslint:
    uses: 'sfusurge/actions-workflows/.github/workflows/npm-publish.yml@v1'
    with:
      workflow-ref: "v1"
      cache-key: "eslint"
      package: "config/eslint"
      publish-gpr: ${{ startsWith(github.ref, 'refs/tags/v') }}
      replace-version: "${{ github.ref_name }}"
