name: Package Workflow
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      publish:
        required: true
        type: boolean
      version:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest 
    name: "Test"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
      
      - name: Install Dependencies
        run: |
          cd "${{ inputs.package }}"
          npm ci

      - name: Run Tests
        run: |
          cd "${{ inputs.package }}"
          npm test

  publish:
    runs-on: ubuntu-latest 
    needs: test
    name: "Publish"
    if: ${{ inputs.publish }}

    permissions: 
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: 'sfusurge'

      - name: Rewrite Package Version
        shell: bash
        if: ${{ inputs.version != '' }}
        run: |
          cd "${{ inputs.package }}"
          jq '.["version"] = ($version | sub("^v(?<version>.*)$"; "\(.version)"))' package.json --arg version '${{ inputs.version }}' > package.json.new
          mv package.json.new package.json

      - name: Publish Package
        shell: bash
        run: |
          cd "${{ inputs.package }}"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
