name: Prettier
on:
  push: {}

jobs:
  prettier:
    uses: 'sfusurge/actions-workflows/.github/workflows/npm-publish.yml@main'
    with:
      workflow-ref: "main"
      cache-key: "${{ github.job }}"
      package: "config/prettier"
      publish-gpr: ${{ startsWith(github.ref, 'refs/tags/v') }}
      replace-version: "${{ github.ref_name }}"
