name: Prettier
on:
  push: {}

jobs:
  prettier:
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      package: "config/prettier"
      publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
      version: "${{ github.ref_name }}"
