name: Surge Scripts
on:
  push: {}

jobs:
  typescript:
    uses: 'sfusurge/actions-workflows/.github/workflows/npm-publish.yml@v1'
    with:
      workflow-ref: "v1"
      cache-key: "surge-scripts"
      package: "package/surge-scripts"
      publish-gpr: ${{ startsWith(github.ref, 'refs/tags/v') }}
      replace-version: "${{ github.ref_name }}"
